[package]
name = "core-watcher"
description = "Watches your CPU cores (and other system metrics) and exports them to Prometheus"
license = "MIT"
version = "1.0.0"
edition = "2024"

[dependencies]
lm-sensors = "0.3.2"
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.2"
sysinfo = "0.36.1"
